"""
Django settings for Scheduler project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '30fkmy2r$_awrrytr3gx5m0s_f+#8_dmtzq*o!t5zrp5qc&&c0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Option.apps.OptionConfig',

    # Third party tool
    'crispy_forms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Scheduler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Scheduler.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DJangoTest',  'USER': 'root',
        'PASSWORD': 'Kamran!12754',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

OPTIONS = [
    # (`key`, `tab`, `value`, `label`, `type`, `order`, `visible`, `style`, `title`)

    ('o_accept_bookings', '70', '1|0::1', '', 'bool', '1', '0', 'checkbox', ''),
    ('o_allow_authorize', '7', '1|0::1', '', 'bool', '18', '1', 'checkbox', 'Allow payments with Authorize.net'),
    ('o_allow_bank', '7', '1|0::1', '', 'bool', '24', '1', 'checkbox', 'Provide Bank account details for wire transfers'),
    ('o_allow_creditcard', '7', '1|0::1', '', 'bool', '23', '1', 'checkbox', 'Collect Credit Card details for offline processing'),
    ('o_allow_paypal', '7', '1|0::1', '', 'bool', '16', '1', 'checkbox', 'Allow payments with PayPal'),
    ('o_authorize_hash', '7', '', '', 'string', '21', '1', 'text', 'Authorize.net hash value'),
    ('o_authorize_key', '7', '', '', 'string', '20', '1', 'text', 'Authorize.net transaction key'),
    ('o_authorize_mid', '7', '', '', 'string', '19', '1', 'text', 'Authorize.net merchant ID'),
    ('o_authorize_tz', '7', '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', '22', '1', 'select', 'Authorize.net time zone'),
    ('o_bank_account', '7', 'Bank of America', '', 'text', '25', '1', 'textarea', 'Bank Account'),
    ('o_bf_address_1', '4', '1|2|3::2', 'No|Yes|Yes (Required)', 'enum', '6', '1', '', ''),
    ('o_bf_address_2', '4', '1|2|3::1', 'No|Yes|Yes (Required)', 'enum', '7', '1', '', ''),
    ('o_bf_captcha', '4', '1|3::3', 'No|Yes (Required)', 'enum', '16', '1', '', ''),
    ('o_bf_city', '4', '1|2|3::2', 'No|Yes|Yes (Required)', 'enum', '12', '1', '', ''),
    ('o_bf_country', '4', '1|2|3::1', 'No|Yes|Yes (Required)', 'enum', '15', '1', '', ''),
    ('o_bf_email', '4', '1|2|3::3', 'No|Yes|Yes (Required)', 'enum', '4', '1', '', ''),
    ('o_bf_name', '4', '1|2|3::3', 'No|Yes|Yes (Required)', 'enum', '3', '1', '', ''),
    ('o_bf_notes', '4', '1|2|3::3', 'No|Yes|Yes (Required)', 'enum', '8', '1', '', ''),
    ('o_bf_phone', '4', '1|2|3::3', 'No|Yes|Yes (Required)', 'enum', '5', '1', '', ''),
    ('o_bf_state', '4', '1|2|3::2', 'No|Yes|Yes (Required)', 'enum', '13', '1', '', ''),
    ('o_bf_terms', '4', '1|3::3', 'No|Yes (Required)', 'enum', '17', '1', '', ''),
    ('o_bf_zip', '4', '1|2|3::2', 'No|Yes|Yes (Required)', 'enum', '14', '1', '', ''),
    ('o_booking_days_earlier', '3', '60', '', 'int', '13', '1', 'number','Accept bookings X days ahead'),
    ('o_booking_earlier', '3', '2', '', 'int', '11', '1', 'number', 'Accept bookings X hours before appointment start time'),
    ('o_cancel_earlier', '3', '2', '', 'int', '12', '1', 'number','Clients can cancel a booking up to X hours before appointment start time'),
    ('o_currency', '1', 'AED|AFN|ALL|AMD|ANG|AOA|ARS|AUD|AWG|AZN|BAM|BBD|BDT|BGN|BHD|BIF|BMD|BND|BOB|BOV|BRL|BSD|BTN|BWP|BYR|BZD|CAD|CDF|CHE|CHF|CHW|CLF|CLP|CNY|COP|COU|CRC|CUC|CUP|CVE|CZK|DJF|DKK|DOP|DZD|EEK|EGP|ERN|ETB|EUR|FJD|FKP|GBP|GEL|GHS|GIP|GMD|GNF|GTQ|GYD|HKD|HNL|HRK|HTG|HUF|IDR|ILS|INR|IQD|IRR|ISK|JMD|JOD|JPY|KES|KGS|KHR|KMF|KPW|KRW|KWD|KYD|KZT|LAK|LBP|LKR|LRD|LSL|LTL|LVL|LYD|MAD|MDL|MGA|MKD|MMK|MNT|MOP|MRO|MUR|MVR|MWK|MXN|MXV|MYR|MZN|NAD|NGN|NIO|NOK|NPR|NZD|OMR|PAB|PEN|PGK|PHP|PKR|PLN|PYG|QAR|RON|RSD|RUB|RWF|SAR|SBD|SCR|SDG|SEK|SGD|SHP|SLL|SOS|SRD|STD|SYP|SZL|THB|TJS|TMT|TND|TOP|TRY|TTD|TWD|TZS|UAH|UGX|USD|USN|USS|UYU|UZS|VEF|VND|VUV|WST|XAF|XAG|XAU|XBA|XBB|XBC|XBD|XCD|XDR|XFU|XOF|XPD|XPF|XPT|XTS|XXX|YER|ZAR|ZMK|ZWL::EUR', '', 'enum', '3', '1', '', ''),
    ('o_datetime_format', '1', 'd.m.Y, H:i|d.m.Y, H:i:s|m.d.Y, H:i|m.d.Y, H:i:s|Y.m.d, H:i|Y.m.d, H:i:s|j.n.Y, H:i|j.n.Y, H:i:s|n.j.Y, H:i|n.j.Y, H:i:s|Y.n.j, H:i|Y.n.j, H:i:s|d/m/Y, H:i|d/m/Y, H:i:s|m/d/Y, H:i|m/d/Y, H:i:s|Y/m/d, H:i|Y/m/d, H:i:s|j/n/Y, H:i|j/n/Y, H:i:s|n/j/Y, H:i|n/j/Y, H:i:s|Y/n/j, H:i|Y/n/j, H:i:s|d-m-Y, H:i|d-m-Y, H:i:s|m-d-Y, H:i|m-d-Y, H:i:s|Y-m-d, H:i|Y-m-d, H:i:s|j-n-Y, H:i|j-n-Y, H:i:s|n-j-Y, H:i|n-j-Y, H:i:s|Y-n-j, H:i|Y-n-j, H:i:s::j/n/Y, H:i', 'd.m.Y, H:i (25.09.2010, 09:51)|d.m.Y, H:i:s (25.09.2010, 09:51:47)|m.d.Y, H:i (09.25.2010, 09:51)|m.d.Y, H:i:s (09.25.2010, 09:51:47)|Y.m.d, H:i (2010.09.25, 09:51)|Y.m.d, H:i:s (2010.09.25, 09:51:47)|j.n.Y, H:i (25.9.2010, 09:51)|j.n.Y, H:i:s (25.9.2010, 09:51:47)|n.j.Y, H:i (9.25.2010, 09:51)|n.j.Y, H:i:s (9.25.2010, 09:51:47)|Y.n.j, H:i (2010.9.25, 09:51)|Y.n.j, H:i:s (2010.9.25, 09:51:47)|d/m/Y, H:i (25/09/2010, 09:51)|d/m/Y, H:i:s (25/09/2010, 09:51:47)|m/d/Y, H:i (09/25/2010, 09:51)|m/d/Y, H:i:s (09/25/2010, 09:51:47)|Y/m/d, H:i (2010/09/25, 09:51)|Y/m/d, H:i:s (2010/09/25, 09:51:47)|j/n/Y, H:i (25/9/2010, 09:51)|j/n/Y, H:i:s (25/9/2010, 09:51:47)|n/j/Y, H:i (9/25/2010, 09:51)|n/j/Y, H:i:s (9/25/2010, 09:51:47)|Y/n/j, H:i (2010/9/25, 09:51)|Y/n/j, H:i:s (2010/9/25, 09:51:47)|d-m-Y, H:i (25-09-2010, 09:51)|d-m-Y, H:i:s (25-09-2010, 09:51:47)|m-d-Y, H:i (09-25-2010, 09:51)|m-d-Y, H:i:s (09-25-2010, 09:51:47)|Y-m-d, H:i (2010-09-25, 09:51)|Y-m-d, H:i:s (2010-09-25, 09:51:47)|j-n-Y, H:i (25-9-2010, 09:51)|j-n-Y, H:i:s (25-9-2010, 09:51:47)|n-j-Y, H:i (9-25-2010, 09:51)|n-j-Y, H:i:s (9-25-2010, 09:51:47)|Y-n-j, H:i (2010-9-25, 09:51)|Y-n-j, H:i:s (2010-9-25, 09:51:47)', 'enum', '8', '1', '', ''),
    ('o_date_format', '1', 'd.m.Y|m.d.Y|Y.m.d|j.n.Y|n.j.Y|Y.n.j|d/m/Y|m/d/Y|Y/m/d|j/n/Y|n/j/Y|Y/n/j|d-m-Y|m-d-Y|Y-m-d|j-n-Y|n-j-Y|Y-n-j::d-m-Y', 'd.m.Y (25.09.2012)|m.d.Y (09.25.2012)|Y.m.d (2012.09.25)|j.n.Y (25.9.2012)|n.j.Y (9.25.2012)|Y.n.j (2012.9.25)|d/m/Y (25/09/2012)|m/d/Y (09/25/2012)|Y/m/d (2012/09/25)|j/n/Y (25/9/2012)|n/j/Y (9/25/2012)|Y/n/j (2012/9/25)|d-m-Y (25-09-2012)|m-d-Y (09-25-2012)|Y-m-d (2012-09-25)|j-n-Y (25-9-2012)|n-j-Y (9-25-2012)|Y-n-j (2012-9-25)', 'enum', '6', '1', '', ''),
    ('o_deposit', '7', '20', '', 'float', '12', '1', 'number', 'Set deposit amount to be collected for each appointment'),
    ('o_deposit_type', '7', 'amount|percent::percent', 'Amount|Percent', 'enum', '14', '0', 'select', ''),
    ('o_disable_payments', '7', '1|0::1', '', 'bool', '4', '1', 'checkbox', 'Check if you want to disable payments and only collect reservation details'),
    ('o_fields_index', '99', '5421691dd3cfd7c5545dfb48d259791e', '', 'string', '', '0', '', ''),
    ('o_hide_prices', '70', '1|0::0', '', 'bool', '2', '0', '', ''),
    ('o_layout', '1', '1|2::2', 'Layout 1 - Employees list|Layout 2 - Services list', 'enum', '1', '1', '', ''),
    ('o_multi_lang', '99', '1|0::0', '', 'enum', '', '0', '', ''),
    ('o_paypal_address', '7', 'paypal_seller@example.com', '', 'string', '17', '1', 'email', 'Paypal address'),
    ('o_reminder_body', '8', 'Dear {Name},\r\r\n\r\r\nYour booking is coming soon!\r\r\n\r\r\nBooking ID: {BookingID}\r\r\n\r\r\nServices\r\r\n{Services}\r\r\n\r\r\nRegards,\r\r\nThe Management', '', 'text', '4', '1', 'height:350px', ''),
    ('o_reminder_email_before', '8', '10', '', 'int', '2', '1', '', ''),
    ('o_reminder_enable', '8', '1|0::1', '', 'bool', '1', '1', '', ''),
    ('o_reminder_sms_hours', '8', '2', '', 'int', '5', '1', '', ''),
    ('o_reminder_sms_message', '8', '{Name}, your booking is coming.', '', 'text', '7', '1', 'height:200px', ''),
    ('o_reminder_subject', '8', 'Booking Reminder', '', 'string', '3', '1', '', ''),
    ('o_send_email', '1', 'mail|smtp::mail', 'PHP mail()|SMTP', 'enum', '11', '1', '', ''),
    ('o_seo_url', '1', '1|0::1', '', 'bool', '20', '1', '', ''),
    ('o_smtp_host', '1', '', '', 'string', '12', '1', '', ''),
    ('o_smtp_pass', '1', '', '', 'string', '15', '1', '', ''),
    ('o_smtp_port', '1', '25', '', 'int', '13', '1', '', ''),
    ('o_smtp_user', '1', '', '', 'string', '14', '1', '', ''),
    ('o_status_if_not_paid', '3', 'confirmed|pending|cancelled::pending', 'Confirmed|Pending|Cancelled', 'enum', '10', '1', 'select', 'Default status for booked dates if not paid'),
    ('o_status_if_paid', '3', 'confirmed|pending::confirmed', 'Confirmed|Pending', 'enum', '9', '1', 'select', 'Default status for booked dates if paid'),
    ('o_step', '3', '5|10|15|20|25|30|35|40|45|50|55|60::30', '', 'enum', '3', '1', 'select', 'Step (in minutes)', ''),
    ('o_tax', '7', '10', '', 'float', '14', '1', 'number', 'Tax amount to be collected for each appointment in %'),
    ('o_thank_you_page', '7', 'http://www.phpjabbers.com/', '', 'string', '26', '1', 'link', 'URL for the web page where your clients will be redirected after PayPal or Authorize.net payment'),
    ('o_theme', '1', 'theme1|theme2|theme3|theme4|theme5|theme6|theme7|theme8|theme9|theme10::theme1', 'Theme 1|Theme 2|Theme 3|Theme 4|Theme 5|Theme 6|Theme 7|Theme 8|Theme 9|Theme 10', 'enum', '3', '1', '', ''),
    ('o_timezone', '1', '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', '10', '1', '', ''),
    ('o_time_format', '1', 'H:i|G:i|h:i|h:i a|h:i A|g:i|g:i a|g:i A::h:i A', 'H:i (09:45)|G:i (9:45)|h:i (09:45)|h:i a (09:45 am)|h:i A (09:45 AM)|g:i (9:45)|g:i a (9:45 am)|g:i A (9:45 AM)', 'enum', '7', '1', '', ''),
    ('o_update_2014_10_07_09_51_20.sql_0612084804f64b008213e771b621ad3e', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2014_10_08_03_30_18.sql_4ba141bed15e487243678218e2939ba0', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2014_10_08_04_21_48.sql_36dc0d6912b34d102764b592f00cc80e', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2014_10_08_06_30_51.sql_633fd2a3c5cd1e3c56d35a53e8779c82', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2014_10_08_06_35_38.sql_72ea049ed2f1f40ee684723990fd668e', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2014_10_16_03_31_01.sql_7e0eb8fb93eb8bdf63341ae5c5d11b38', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_01_29_10_06_23.sql_0a30b79c25524e8617c8b6e380da668e', '99', '2015-04-16 19:06:59', '', 'string', '', '1', '', ''),
    ('o_update_2015_03_25_08_12_45.sql_25730f7437d4dbac33c7cf2a914501ed', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_03_26_03_40_01.sql_5e15fce784126bc530bf31cfb6ab8b14', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_03_27_02_24_19.sql_7a2f47a7284a7f2da64421885605054f', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_03_27_03_20_03.sql_20ae4e6985a450c91e3b8c6d1e55290a', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_01_10_18_00.sql_cf2ebb88493023c362643c328812333f', '99', '2015-04-16 19:07:00', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_06_14_45_32.sql_094fdf8f771393116ae90512826cfe55', '99', '2015-04-16 19:06:56', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_07_09_42_47.sql_532562b31cac076cd503dcf2a39a01fa', '99', '2015-04-16 19:07:01', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_09_03_33_52.sql_75a703d2d80479b84ed85dcbf8e8e086', '99', '2015-04-16 19:06:56', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_10_09_52_22.sql_491eccca03e0c5948a62e5bb7d4d9344', '99', '2015-04-16 19:07:01', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_13_09_20_20.sql_caee7a7ae6f8c5e53545bd257e0c3f1b', '99', '2015-04-16 19:07:01', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_14_10_57_15.sql_269de580611f0a73eae17ca4f0747745', '99', '2015-04-16 19:07:01', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_16_07_18_34.sql_3117dd99eb4b34c7d8b7c723b24a4b69', '99', '2015-04-16 19:07:01', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_21_09_15_05.sql_7d1b262b587bf3f1e1eeff6e91e2ef34', '99', '2015-04-22 10:25:32', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_22_09_39_05.sql_8ba59f8291b21b2d98a3ea257717e754', '99', '2015-11-24 14:07:29', '', 'string', '', '1', '', ''),
    ('o_update_2015_04_27_11_49_31.sql_ad738aa88f92dfc0c0582ad6f5954838', '99', '2015-11-24 14:07:36', '', 'string', '', '1', '', ''),
    ('o_update_2015_06_26_04_49_11.sql_4922d7c744ad44b4189c13d5f0cbd236', '99', '2015-11-24 14:07:39', '', 'string', '', '1', '', ''),
    ('o_update_2015_06_26_04_55_22.sql_7b6d4e912c0de03aed872ece31472b67', '99', '2015-11-24 14:07:42', '', 'string', '', '1', '', ''),
    ('o_update_2015_10_20_09_46_51.sql_f56f4dafbe13e582534af0acee9b82c5', '99', '2015-11-24 14:07:45', '', 'string', '', '1', '', ''),
    ('o_update_2015_10_22_03_52_35.sql_8442eb0adb6de65c9a738d765acb17ae', '99', '2015-11-24 14:07:47', '', 'string', '', '1', '', ''),
    ('o_update_2015_10_23_07_53_38.sql_631d5d4d90f3ff216d65e0b2fe6ea8c1', '99', '2015-11-24 14:07:50', '', 'string', '', '1', '', ''),
    ('o_update_2015_10_30_07_12_46.sql_6ef0f58825ccefb2909b555da2f50ee8', '99', '2015-11-24 14:07:54', '', 'string', '', '1', '', ''),
    ('o_update_2015_11_17_02_44_57.sql_efa144ff0931d5642df85e64d6a8b7d4', '99', '2015-11-24 14:07:59', '', 'string', '', '1', '', ''),
    ('o_update_2015_11_17_07_05_23.sql_8f2437587f1cfbe362f3dfb40a482512', '99', '2015-11-24 14:08:03', '', 'string', '', '1', '', ''),
    ('o_update_2015_11_19_17_50_18.sql_126b330564adc065538b7b26fe072cc6', '99', '2015-11-24 14:08:07', '', 'string', '', '1', '', ''),
    ('o_update_2015_11_23_18_01_33.sql_f529c29b4a2cdf867067ae15d279207d', '99', '2015-11-24 14:08:10', '', 'string', '', '1', '', ''),
    ('o_update_2015_11_24_10_09_17.sql_d00082bcfa5a6a4307f7a458874f2885', '99', '2015-11-24 14:08:14', '', 'string', '', '1', '', ''),
    ('o_update_2015_12_30_08_46_57.sql_a8fa008b0080beace6316b1813d4582b', '99', '2017-04-25 18:54:30', '', 'string', '', '1', '', ''),
    ('o_update_2016_01_04_07_03_00.sql_212c509d6b5f9f0a364b3be38fb7e845', '99', '2017-04-25 18:54:39', '', 'string', '', '1', '', ''),
    ('o_update_2016_01_04_09_08_31.sql_e67ea087af5b834e71c8959076a25574', '99', '2017-04-25 18:56:26', '', 'string', '', '1', '', ''),
    ('o_update_2016_01_08_14_33_51.sql_54193e6a2feefabb762dd1aac6ac65b7', '99', '2017-04-25 18:56:36', '', 'string', '', '1', '', ''),
    ('o_update_2016_01_11_00_00_00.sql_23e2b7aa9bacf4632cb8a2fc807f479e', '99', '2017-04-25 18:56:44', '', 'string', '', '1', '', ''),
    ('o_update_2016_02_05_15_10_22.sql_3e4b3cea79005b43298562806e0775f2', '99', '2017-04-25 18:57:00', '', 'string', '', '1', '', ''),
    ('o_update_2016_03_07_13_35_49.sql_f130bc1c094d96b8db7ad61ef9809e1c', '99', '2017-04-25 18:57:21', '', 'string', '', '1', '', ''),
    ('o_update_2016_03_08_15_21_41.sql_899b63fd0accf149852c35a3baa32197', '99', '2017-04-25 18:57:28', '', 'string', '', '1', '', ''),
    ('o_update_2016_03_18_11_26_43.sql_523bca50453fd774a4973ba5ae9d46f8', '99', '2017-04-25 18:57:38', '', 'string', '', '1', '', ''),
    ('o_update_2016_05_03_17_14_31.sql_7465cbb318ccf9c26a4a029d25c8280b', '99', '2017-04-25 18:57:45', '', 'string', '', '1', '', ''),
    ('o_update_2016_07_08_14_41_22.sql_81bffbcecbb14bdfc634ac4d1ec0f505', '99', '2017-04-25 18:57:52', '', 'string', '', '1', '', ''),
    ('o_update_2016_08_23_07_54_31.sql_1113e5f87206945b185be402930d68fc', '99', '2017-04-25 18:57:58', '', 'string', '', '1', '', ''),
    ('o_update_2016_08_23_09_53_59.sql_80ebbbf950b1e42075b1d37b866fef96', '99', '2017-04-25 18:58:05', '', 'string', '', '1', '', ''),
    ('o_update_2017_02_07_06_48_09.sql_643b392f892828dcd0b420a4e48421f9', '99', '2017-04-25 18:58:15', '', 'string', '', '1', '', ''),
    ('o_update_2017_03_09_04_48_07.sql_b7c29c38e702ffb6784c39338bf1efbd', '99', '2017-04-25 18:58:23', '', 'string', '', '1', '', ''),
    ('o_update_2017_03_09_05_29_04.sql_87df3eadc436ce256ea7d827dbb36377', '99', '2017-04-25 18:58:31', '', 'string', '', '1', '', ''),
    ('o_update_2017_03_13_13_13_13.sql_a8e6e7c1ad2f61f681ccefbfb341981c', '99', '2017-04-25 18:58:37', '', 'string', '', '1', '', ''),
    ('o_week_numbers', '1', '1|0::1', '', 'bool', '19', '1', '', ''),
    ('o_week_start', '1', '0|1|2|3|4|5|6::1', 'Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday', 'enum', '9', '1', '', ''),
    ('private_key', '99', 'nTa3LQSS3Mu9qASaPVqyLKn0wS3gYmBuGPajGBezX7FKt8KTu6ulHKBtLoKUyA9TpWnUQEgOHmjj/ppnhKEegGM8v1cWdsguV55QO97Rr5sZV3qwMFKvG7VFPq1MNXaXRXvGnPBM9JoHh5Tofkv8Jsu08ow8Y27v9qFu20Ux1FdhDF9K14KuIPeuZ1crLWNmLW+uH6KdDvm2aYR34Zzx/YG8YcB3PpQKN+uNFOGrrCyy0a3WEQdMuMbfADNovyk7BKQszh956/wcaEp1b6JJJW+8o+R6F4Ef3GDYX8h9fV6fYezDKMPAdScUTCtVaQHvRW9MH9IeYyGJ0MzZrEaLVw==', '', 'string', '', '1', '')
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
